name: .NET Core Desktop

on:
  push:
    branches: [ "development", "feature/**" ]
  pull_request:
    branches: [ "development", "feature/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Build project
      run: dotnet build Profile_Service.sln

  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    # - name: Build project
    #   run: dotnet build ${{ github.workspace }}/Profile_Service.XUnit/Profile_Service.XUnit.csproj

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ github.workspace }}/Profile_Service.XUnit/Profile_Service.XUnit.csproj