name: .NET Core Desktop

on:
  push:
    branches: [ "development", "feature/**" ]
  pull_request:
    branches: [ "development", "feature/**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Build project
      run: dotnet build Profile_Service.sln

  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    # - name: Build project
    #   run: dotnet build ${{ github.workspace }}/Profile_Service.XUnit/Profile_Service.XUnit.csproj

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test ${{ github.workspace }}/Profile_Service.XUnit/Profile_Service.XUnit.csproj

  SonarCloud_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
        with:
          projectBaseDir: ${{ github.workspace }}/Profile_Service/
          args:
            -Dsonar.projectKey=De-Oefenpraktijk_Profile_Service
            -Dsonar.organization=de-oefenpraktijk
            -Dsonar.language=csharp